version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_HOST_NAME : "kafka"
      KAFKA_CREATE_TOPICS: "patientBookAppointment:1:1,confirmAppointment:1:1,medicineDelivery:1:1,appointmentCompleted:1:1,visitComplete:1:1,hospitalVisit:1:1"
      KAFKA_ZOOKEEPER_CONNECT : zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: SSL://:9093,INSIDE://kafka:9092,OUTSIDE:// 172.25.0.1:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

#  ourimage:
#    image: patientimage:latest
#    depends_on:
#      - kafka
#      - zookeeper
#    ports:
#      - "9000:9000"

